-- AlterTable
ALTER TABLE "SiteSettings" ADD COLUMN "qrTemplateImage" TEXT;
ALTER TABLE "SiteSettings" ADD COLUMN "qrBoxLeft" REAL NOT NULL DEFAULT 31.3;
ALTER TABLE "SiteSettings" ADD COLUMN "qrBoxTop" REAL NOT NULL DEFAULT 44.8;
ALTER TABLE "SiteSettings" ADD COLUMN "qrBoxWidth" REAL NOT NULL DEFAULT 36.0;
ALTER TABLE "SiteSettings" ADD COLUMN "qrBoxHeight" REAL NOT NULL DEFAULT 27.2;
